/* Generated by re2c 0.9.3 on Thu Jun 01 11:25:57 2006 */
#line 1 "scanner.re"
#include <string.h>
#include <malloc.h>
#include <stdlib.h>
#include "dehsupp.h"

#define	BSIZE	8192

#define	YYCTYPE		uchar
#define	YYCURSOR	cursor
#define	YYLIMIT		s->lim
#define	YYMARKER	s->ptr
#define	YYFILL(n)	{cursor = fill(s, cursor);}

#define	RET(i)	{s->cur = cursor; return i;}

uchar *fill(Scanner *s, uchar *cursor)
{
	if(!s->eof)
	{
		ptrdiff_t cnt = s->tok - s->bot;
		if(cnt)
		{
			memcpy(s->bot, s->tok, s->lim - s->tok);
			s->tok = s->bot;
			s->ptr -= cnt;
			cursor -= cnt;
			s->pos -= cnt;
			s->lim -= cnt;
		}
		if((s->top - s->lim) < BSIZE)
		{
			uchar *buf = (uchar*) malloc(((s->lim - s->bot) + BSIZE)*sizeof(uchar));
			memcpy(buf, s->tok, s->lim - s->tok);
			s->tok = buf;
			s->ptr = &buf[s->ptr - s->bot];
			cursor = &buf[cursor - s->bot];
			s->pos = &buf[s->pos - s->bot];
			s->lim = &buf[s->lim - s->bot];
			s->top = &s->lim[BSIZE];
			free(s->bot);
			s->bot = buf;
		}
		if((cnt = fread((char*) s->lim, 1, BSIZE, s->fd)) != BSIZE)
		{
			s->eof = &s->lim[cnt]; *(s->eof)++ = '\n';
		}
		s->lim += cnt;
	}
	return cursor;
}

int scan(Scanner *s)
{
	uchar *cursor = s->cur;
std:
	s->tok = cursor;
#line 64 "scanner.re"



#line 7 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy0;
yy1:	++YYCURSOR;
yy0:
	if((YYLIMIT - YYCURSOR) < 13) YYFILL(13);
	yych = *YYCURSOR;
	switch(yych){
	case '\t':	case '\v':
	case '\f':	case ' ':	goto yy22;
	case '\n':	goto yy46;
	case '"':	goto yy20;
	case '&':	goto yy28;
	case '(':	goto yy36;
	case '*':	goto yy34;
	case '+':	goto yy32;
	case ',':	goto yy40;
	case '-':	goto yy30;
	case '/':	goto yy2;
	case '0':	goto yy17;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy19;
	case ';':	goto yy44;
	case 'A':	goto yy7;
	case 'B':	case 'E':	case 'G':
	case 'H':	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':	case 'P':
	case 'Q':	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	case '_':	case 'a':
	case 'b':
	case 'c':
	case 'd':	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy16;
	case 'C':	goto yy9;
	case 'D':	goto yy13;
	case 'F':	goto yy14;
	case 'I':	goto yy11;
	case 'O':	goto yy8;
	case 'R':	goto yy15;
	case 'S':	goto yy10;
	case 'T':	goto yy12;
	case '^':	goto yy26;
	case 'e':	goto yy4;
	case 'p':	goto yy6;
	case '{':	goto yy42;
	case '|':	goto yy24;
	case '}':	goto yy38;
	default:	goto yy48;
	}
yy2:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '*')	goto yy198;
	if(yych == '/')	goto yy196;
	goto yy3;
yy3:
#line 107 "scanner.re"
{ RET(DIVIDE); }
#line 97 "scanner.c"
yy4:	++YYCURSOR;
	if((yych = *YYCURSOR) == 'n')	goto yy192;
	goto yy70;
yy5:
#line 91 "scanner.re"
{ RET(SYM); }
#line 104 "scanner.c"
yy6:	yych = *++YYCURSOR;
	if(yych == 'r')	goto yy187;
	goto yy70;
yy7:	yych = *++YYCURSOR;
	if(yych == 'c')	goto yy175;
	goto yy70;
yy8:	yych = *++YYCURSOR;
	if(yych == 'r')	goto yy156;
	goto yy70;
yy9:	yych = *++YYCURSOR;
	if(yych == 'o')	goto yy147;
	goto yy70;
yy10:	yych = *++YYCURSOR;
	if(yych <= 'p'){
		if(yych <= 'n')	goto yy70;
		if(yych <= 'o')	goto yy121;
		goto yy122;
	} else {
		if(yych == 't')	goto yy123;
		goto yy70;
	}
yy11:	yych = *++YYCURSOR;
	if(yych == 'n')	goto yy112;
	goto yy70;
yy12:	yych = *++YYCURSOR;
	if(yych == 'h')	goto yy103;
	goto yy70;
yy13:	yych = *++YYCURSOR;
	if(yych == 'e')	goto yy93;
	goto yy70;
yy14:	yych = *++YYCURSOR;
	if(yych == 'i')	goto yy83;
	goto yy70;
yy15:	yych = *++YYCURSOR;
	if(yych == 'e')	goto yy71;
	goto yy70;
yy16:	yych = *++YYCURSOR;
	goto yy70;
yy17:	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'X')	goto yy66;
	if(yych == 'x')	goto yy66;
	goto yy65;
yy18:
#line 94 "scanner.re"
{ RET(NUM); }
#line 151 "scanner.c"
yy19:	yych = *++YYCURSOR;
	goto yy63;
yy20:	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych != '\n')	goto yy52;
	goto yy21;
yy21:
#line 124 "scanner.re"
{
		printf("unexpected character: %c\n", *s->tok);
		goto std;
		}
#line 164 "scanner.c"
yy22:	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy50;
yy23:
#line 99 "scanner.re"
{ goto std; }
#line 170 "scanner.c"
yy24:	++YYCURSOR;
	goto yy25;
yy25:
#line 101 "scanner.re"
{ RET(OR); }
#line 176 "scanner.c"
yy26:	++YYCURSOR;
	goto yy27;
yy27:
#line 102 "scanner.re"
{ RET(XOR); }
#line 182 "scanner.c"
yy28:	++YYCURSOR;
	goto yy29;
yy29:
#line 103 "scanner.re"
{ RET(AND); }
#line 188 "scanner.c"
yy30:	++YYCURSOR;
	goto yy31;
yy31:
#line 104 "scanner.re"
{ RET(MINUS); }
#line 194 "scanner.c"
yy32:	++YYCURSOR;
	goto yy33;
yy33:
#line 105 "scanner.re"
{ RET(PLUS); }
#line 200 "scanner.c"
yy34:	++YYCURSOR;
	goto yy35;
yy35:
#line 106 "scanner.re"
{ RET(MULTIPLY); }
#line 206 "scanner.c"
yy36:	++YYCURSOR;
	goto yy37;
yy37:
#line 108 "scanner.re"
{ RET(LPAREN); }
#line 212 "scanner.c"
yy38:	++YYCURSOR;
	goto yy39;
yy39:
#line 109 "scanner.re"
{ RET(RPAREN); }
#line 218 "scanner.c"
yy40:	++YYCURSOR;
	goto yy41;
yy41:
#line 110 "scanner.re"
{ RET(COMMA); }
#line 224 "scanner.c"
yy42:	++YYCURSOR;
	goto yy43;
yy43:
#line 111 "scanner.re"
{ RET(LBRACE); }
#line 230 "scanner.c"
yy44:	++YYCURSOR;
	goto yy45;
yy45:
#line 113 "scanner.re"
{ RET(SEMICOLON); }
#line 236 "scanner.c"
yy46:	++YYCURSOR;
	goto yy47;
yy47:
#line 117 "scanner.re"
{
		if(cursor == s->eof) RET(EOI);
		s->pos = cursor; s->line++;
		goto std;
		}
#line 246 "scanner.c"
yy48:	yych = *++YYCURSOR;
	goto yy21;
yy49:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy50;
yy50:	if(yych <= '\n'){
		if(yych == '\t')	goto yy49;
		goto yy23;
	} else {
		if(yych <= '\f')	goto yy49;
		if(yych == ' ')	goto yy49;
		goto yy23;
	}
yy51:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy52;
yy52:	if(yych <= '!'){
		if(yych != '\n')	goto yy51;
		goto yy53;
	} else {
		if(yych <= '"')	goto yy55;
		if(yych == '\\')	goto yy54;
		goto yy51;
	}
yy53:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 1:	goto yy18;
	case 0:	goto yy3;
	case 2:	goto yy21;
	}
yy54:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'b'){
		if(yych <= '7'){
			if(yych <= '&'){
				if(yych == '"')	goto yy51;
				goto yy53;
			} else {
				if(yych <= '\'')	goto yy51;
				if(yych <= '/')	goto yy53;
				goto yy58;
			}
		} else {
			if(yych <= '['){
				if(yych == '?')	goto yy51;
				goto yy53;
			} else {
				if(yych <= '\\')	goto yy51;
				if(yych <= '`')	goto yy53;
				goto yy51;
			}
		}
	} else {
		if(yych <= 'r'){
			if(yych <= 'm'){
				if(yych == 'f')	goto yy51;
				goto yy53;
			} else {
				if(yych <= 'n')	goto yy51;
				if(yych <= 'q')	goto yy53;
				goto yy51;
			}
		} else {
			if(yych <= 'u'){
				if(yych == 't')	goto yy51;
				goto yy53;
			} else {
				if(yych <= 'v')	goto yy51;
				if(yych == 'x')	goto yy57;
				goto yy53;
			}
		}
	}
yy55:	++YYCURSOR;
	goto yy56;
yy56:
#line 97 "scanner.re"
{ RET(STRING); }
#line 331 "scanner.c"
yy57:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy53;
		if(yych <= '9')	goto yy60;
		goto yy53;
	} else {
		if(yych <= 'F')	goto yy60;
		if(yych <= '`')	goto yy53;
		if(yych <= 'f')	goto yy60;
		goto yy53;
	}
yy58:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy59;
yy59:	if(yych <= '"'){
		if(yych == '\n')	goto yy53;
		if(yych <= '!')	goto yy51;
		goto yy55;
	} else {
		if(yych <= '7'){
			if(yych <= '/')	goto yy51;
			goto yy58;
		} else {
			if(yych == '\\')	goto yy54;
			goto yy51;
		}
	}
yy60:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy61;
yy61:	if(yych <= '9'){
		if(yych <= '!'){
			if(yych == '\n')	goto yy53;
			goto yy51;
		} else {
			if(yych <= '"')	goto yy55;
			if(yych <= '/')	goto yy51;
			goto yy60;
		}
	} else {
		if(yych <= '['){
			if(yych <= '@')	goto yy51;
			if(yych <= 'F')	goto yy60;
			goto yy51;
		} else {
			if(yych <= '\\')	goto yy54;
			if(yych <= '`')	goto yy51;
			if(yych <= 'f')	goto yy60;
			goto yy51;
		}
	}
yy62:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy63;
yy63:	if(yych <= '/')	goto yy18;
	if(yych <= '9')	goto yy62;
	goto yy18;
yy64:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy65;
yy65:	if(yych <= '/')	goto yy18;
	if(yych <= '9')	goto yy64;
	goto yy18;
yy66:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy53;
		if(yych >= ':')	goto yy53;
		goto yy67;
	} else {
		if(yych <= 'F')	goto yy67;
		if(yych <= '`')	goto yy53;
		if(yych >= 'g')	goto yy53;
		goto yy67;
	}
yy67:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy68;
yy68:	if(yych <= '@'){
		if(yych <= '/')	goto yy18;
		if(yych <= '9')	goto yy67;
		goto yy18;
	} else {
		if(yych <= 'F')	goto yy67;
		if(yych <= '`')	goto yy18;
		if(yych <= 'f')	goto yy67;
		goto yy18;
	}
yy69:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy70;
yy70:	if(yych <= 'Z'){
		if(yych <= '/')	goto yy5;
		if(yych <= '9')	goto yy69;
		if(yych <= '@')	goto yy5;
		goto yy69;
	} else {
		if(yych <= '_'){
			if(yych <= '^')	goto yy5;
			goto yy69;
		} else {
			if(yych <= '`')	goto yy5;
			if(yych <= 'z')	goto yy69;
			goto yy5;
		}
	}
yy71:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy70;
	goto yy72;
yy72:	yych = *++YYCURSOR;
	if(yych != 'd')	goto yy70;
	goto yy73;
yy73:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy70;
	goto yy74;
yy74:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy70;
	goto yy75;
yy75:	yych = *++YYCURSOR;
	if(yych != 'S')	goto yy70;
	goto yy76;
yy76:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy70;
	goto yy77;
yy77:	yych = *++YYCURSOR;
	if(yych != 'y')	goto yy70;
	goto yy78;
yy78:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy70;
	goto yy79;
yy79:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy70;
	goto yy80;
yy80:	yych = *++YYCURSOR;
	if(yych != 's')	goto yy70;
	goto yy81;
yy81:	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z'){
		if(yych <= '/')	goto yy82;
		if(yych <= '9')	goto yy69;
		if(yych >= 'A')	goto yy69;
		goto yy82;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy69;
			goto yy82;
		} else {
			if(yych <= '`')	goto yy82;
			if(yych <= 'z')	goto yy69;
			goto yy82;
		}
	}
yy82:
#line 89 "scanner.re"
{ RET(RenderStyles); }
#line 501 "scanner.c"
yy83:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy70;
	goto yy84;
yy84:	yych = *++YYCURSOR;
	if(yych != 's')	goto yy70;
	goto yy85;
yy85:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy70;
	goto yy86;
yy86:	yych = *++YYCURSOR;
	if(yych != 'S')	goto yy70;
	goto yy87;
yy87:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy70;
	goto yy88;
yy88:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy70;
	goto yy89;
yy89:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy70;
	goto yy90;
yy90:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy70;
	goto yy91;
yy91:	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z'){
		if(yych <= '/')	goto yy92;
		if(yych <= '9')	goto yy69;
		if(yych >= 'A')	goto yy69;
		goto yy92;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy69;
			goto yy92;
		} else {
			if(yych <= '`')	goto yy92;
			if(yych <= 'z')	goto yy69;
			goto yy92;
		}
	}
yy92:
#line 88 "scanner.re"
{ RET(FirstState); }
#line 545 "scanner.c"
yy93:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy70;
	goto yy94;
yy94:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy70;
	goto yy95;
yy95:	yych = *++YYCURSOR;
	if(yych != 'h')	goto yy70;
	goto yy96;
yy96:	yych = *++YYCURSOR;
	if(yych != 'S')	goto yy70;
	goto yy97;
yy97:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy70;
	goto yy98;
yy98:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy70;
	goto yy99;
yy99:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy70;
	goto yy100;
yy100:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy70;
	goto yy101;
yy101:	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z'){
		if(yych <= '/')	goto yy102;
		if(yych <= '9')	goto yy69;
		if(yych >= 'A')	goto yy69;
		goto yy102;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy69;
			goto yy102;
		} else {
			if(yych <= '`')	goto yy102;
			if(yych <= 'z')	goto yy69;
			goto yy102;
		}
	}
yy102:
#line 86 "scanner.re"
{ RET(DeathState); }
#line 589 "scanner.c"
yy103:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy70;
	goto yy104;
yy104:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy70;
	goto yy105;
yy105:	yych = *++YYCURSOR;
	if(yych != 'g')	goto yy70;
	goto yy106;
yy106:	yych = *++YYCURSOR;
	if(yych != 'B')	goto yy70;
	goto yy107;
yy107:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy70;
	goto yy108;
yy108:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy70;
	goto yy109;
yy109:	yych = *++YYCURSOR;
	if(yych != 's')	goto yy70;
	goto yy110;
yy110:	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z'){
		if(yych <= '/')	goto yy111;
		if(yych <= '9')	goto yy69;
		if(yych >= 'A')	goto yy69;
		goto yy111;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy69;
			goto yy111;
		} else {
			if(yych <= '`')	goto yy111;
			if(yych <= 'z')	goto yy69;
			goto yy111;
		}
	}
yy111:
#line 85 "scanner.re"
{ RET(ThingBits); }
#line 630 "scanner.c"
yy112:	yych = *++YYCURSOR;
	if(yych != 'f')	goto yy70;
	goto yy113;
yy113:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy70;
	goto yy114;
yy114:	yych = *++YYCURSOR;
	if(yych != 'N')	goto yy70;
	goto yy115;
yy115:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy70;
	goto yy116;
yy116:	yych = *++YYCURSOR;
	if(yych != 'm')	goto yy70;
	goto yy117;
yy117:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy70;
	goto yy118;
yy118:	yych = *++YYCURSOR;
	if(yych != 's')	goto yy70;
	goto yy119;
yy119:	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z'){
		if(yych <= '/')	goto yy120;
		if(yych <= '9')	goto yy69;
		if(yych >= 'A')	goto yy69;
		goto yy120;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy69;
			goto yy120;
		} else {
			if(yych <= '`')	goto yy120;
			if(yych <= 'z')	goto yy69;
			goto yy120;
		}
	}
yy120:
#line 84 "scanner.re"
{ RET(InfoNames); }
#line 671 "scanner.c"
yy121:	yych = *++YYCURSOR;
	if(yych == 'u')	goto yy140;
	goto yy70;
yy122:	yych = *++YYCURSOR;
	if(yych == 'a')	goto yy131;
	goto yy70;
yy123:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy70;
	goto yy124;
yy124:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy70;
	goto yy125;
yy125:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy70;
	goto yy126;
yy126:	yych = *++YYCURSOR;
	if(yych != 'M')	goto yy70;
	goto yy127;
yy127:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy70;
	goto yy128;
yy128:	yych = *++YYCURSOR;
	if(yych != 'p')	goto yy70;
	goto yy129;
yy129:	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z'){
		if(yych <= '/')	goto yy130;
		if(yych <= '9')	goto yy69;
		if(yych >= 'A')	goto yy69;
		goto yy130;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy69;
			goto yy130;
		} else {
			if(yych <= '`')	goto yy130;
			if(yych <= 'z')	goto yy69;
			goto yy130;
		}
	}
yy130:
#line 82 "scanner.re"
{ RET(StateMap); }
#line 715 "scanner.c"
yy131:	yych = *++YYCURSOR;
	if(yych != 'w')	goto yy70;
	goto yy132;
yy132:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy70;
	goto yy133;
yy133:	yych = *++YYCURSOR;
	if(yych != 'S')	goto yy70;
	goto yy134;
yy134:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy70;
	goto yy135;
yy135:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy70;
	goto yy136;
yy136:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy70;
	goto yy137;
yy137:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy70;
	goto yy138;
yy138:	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z'){
		if(yych <= '/')	goto yy139;
		if(yych <= '9')	goto yy69;
		if(yych >= 'A')	goto yy69;
		goto yy139;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy69;
			goto yy139;
		} else {
			if(yych <= '`')	goto yy139;
			if(yych <= 'z')	goto yy69;
			goto yy139;
		}
	}
yy139:
#line 87 "scanner.re"
{ RET(SpawnState); }
#line 756 "scanner.c"
yy140:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy70;
	goto yy141;
yy141:	yych = *++YYCURSOR;
	if(yych != 'd')	goto yy70;
	goto yy142;
yy142:	yych = *++YYCURSOR;
	if(yych != 'M')	goto yy70;
	goto yy143;
yy143:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy70;
	goto yy144;
yy144:	yych = *++YYCURSOR;
	if(yych != 'p')	goto yy70;
	goto yy145;
yy145:	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z'){
		if(yych <= '/')	goto yy146;
		if(yych <= '9')	goto yy69;
		if(yych >= 'A')	goto yy69;
		goto yy146;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy69;
			goto yy146;
		} else {
			if(yych <= '`')	goto yy146;
			if(yych <= 'z')	goto yy69;
			goto yy146;
		}
	}
yy146:
#line 83 "scanner.re"
{ RET(SoundMap); }
#line 791 "scanner.c"
yy147:	yych = *++YYCURSOR;
	if(yych != 'd')	goto yy70;
	goto yy148;
yy148:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy70;
	goto yy149;
yy149:	yych = *++YYCURSOR;
	if(yych != 'P')	goto yy70;
	goto yy150;
yy150:	yych = *++YYCURSOR;
	if(yych != 'C')	goto yy70;
	goto yy151;
yy151:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy70;
	goto yy152;
yy152:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy70;
	goto yy153;
yy153:	yych = *++YYCURSOR;
	if(yych != 'v')	goto yy70;
	goto yy154;
yy154:	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z'){
		if(yych <= '/')	goto yy155;
		if(yych <= '9')	goto yy69;
		if(yych >= 'A')	goto yy69;
		goto yy155;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy69;
			goto yy155;
		} else {
			if(yych <= '`')	goto yy155;
			if(yych <= 'z')	goto yy69;
			goto yy155;
		}
	}
yy155:
#line 80 "scanner.re"
{ RET(CodePConv); }
#line 832 "scanner.c"
yy156:	yych = *++YYCURSOR;
	if(yych != 'g')	goto yy70;
	goto yy157;
yy157:	yych = *++YYCURSOR;
	if(yych == 'H')	goto yy158;
	if(yych == 'S')	goto yy159;
	goto yy70;
yy158:	yych = *++YYCURSOR;
	if(yych == 'e')	goto yy168;
	goto yy70;
yy159:	yych = *++YYCURSOR;
	if(yych != 'p')	goto yy70;
	goto yy160;
yy160:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy70;
	goto yy161;
yy161:	yych = *++YYCURSOR;
	if(yych != 'N')	goto yy70;
	goto yy162;
yy162:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy70;
	goto yy163;
yy163:	yych = *++YYCURSOR;
	if(yych != 'm')	goto yy70;
	goto yy164;
yy164:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy70;
	goto yy165;
yy165:	yych = *++YYCURSOR;
	if(yych != 's')	goto yy70;
	goto yy166;
yy166:	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z'){
		if(yych <= '/')	goto yy167;
		if(yych <= '9')	goto yy69;
		if(yych >= 'A')	goto yy69;
		goto yy167;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy69;
			goto yy167;
		} else {
			if(yych <= '`')	goto yy167;
			if(yych <= 'z')	goto yy69;
			goto yy167;
		}
	}
yy167:
#line 81 "scanner.re"
{ RET(OrgSprNames); }
#line 883 "scanner.c"
yy168:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy70;
	goto yy169;
yy169:	yych = *++YYCURSOR;
	if(yych != 'g')	goto yy70;
	goto yy170;
yy170:	yych = *++YYCURSOR;
	if(yych != 'h')	goto yy70;
	goto yy171;
yy171:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy70;
	goto yy172;
yy172:	yych = *++YYCURSOR;
	if(yych != 's')	goto yy70;
	goto yy173;
yy173:	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z'){
		if(yych <= '/')	goto yy174;
		if(yych <= '9')	goto yy69;
		if(yych >= 'A')	goto yy69;
		goto yy174;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy69;
			goto yy174;
		} else {
			if(yych <= '`')	goto yy174;
			if(yych <= 'z')	goto yy69;
			goto yy174;
		}
	}
yy174:
#line 78 "scanner.re"
{ RET(OrgHeights); }
#line 918 "scanner.c"
yy175:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy70;
	goto yy176;
yy176:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy70;
	goto yy177;
yy177:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy70;
	goto yy178;
yy178:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy70;
	goto yy179;
yy179:	yych = *++YYCURSOR;
	if(yych == 'L')	goto yy182;
	if(yych != 's')	goto yy70;
	goto yy180;
yy180:	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z'){
		if(yych <= '/')	goto yy181;
		if(yych <= '9')	goto yy69;
		if(yych >= 'A')	goto yy69;
		goto yy181;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy69;
			goto yy181;
		} else {
			if(yych <= '`')	goto yy181;
			if(yych <= 'z')	goto yy69;
			goto yy181;
		}
	}
yy181:
#line 77 "scanner.re"
{ RET(Actions); }
#line 954 "scanner.c"
yy182:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy70;
	goto yy183;
yy183:	yych = *++YYCURSOR;
	if(yych != 's')	goto yy70;
	goto yy184;
yy184:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy70;
	goto yy185;
yy185:	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z'){
		if(yych <= '/')	goto yy186;
		if(yych <= '9')	goto yy69;
		if(yych >= 'A')	goto yy69;
		goto yy186;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy69;
			goto yy186;
		} else {
			if(yych <= '`')	goto yy186;
			if(yych <= 'z')	goto yy69;
			goto yy186;
		}
	}
yy186:
#line 79 "scanner.re"
{ RET(ActionList); }
#line 983 "scanner.c"
yy187:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy70;
	goto yy188;
yy188:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy70;
	goto yy189;
yy189:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy70;
	goto yy190;
yy190:	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z'){
		if(yych <= '/')	goto yy191;
		if(yych <= '9')	goto yy69;
		if(yych >= 'A')	goto yy69;
		goto yy191;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy69;
			goto yy191;
		} else {
			if(yych <= '`')	goto yy191;
			if(yych <= 'z')	goto yy69;
			goto yy191;
		}
	}
yy191:
#line 76 "scanner.re"
{ RET(PRINT); }
#line 1012 "scanner.c"
yy192:	yych = *++YYCURSOR;
	if(yych != 'd')	goto yy70;
	goto yy193;
yy193:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy70;
	goto yy194;
yy194:	++YYCURSOR;
	if((yych = *YYCURSOR) <= 'Z'){
		if(yych <= '/')	goto yy195;
		if(yych <= '9')	goto yy69;
		if(yych >= 'A')	goto yy69;
		goto yy195;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy69;
			goto yy195;
		} else {
			if(yych <= '`')	goto yy195;
			if(yych <= 'z')	goto yy69;
			goto yy195;
		}
	}
yy195:
#line 75 "scanner.re"
{ RET(ENDL); }
#line 1038 "scanner.c"
yy196:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy197;
yy197:	if(yych == '\n')	goto yy200;
	goto yy196;
yy198:	++YYCURSOR;
	goto yy199;
yy199:
#line 67 "scanner.re"
{ goto comment; }
#line 1051 "scanner.c"
yy200:	++YYCURSOR;
	goto yy201;
yy201:
#line 69 "scanner.re"
{
		if(cursor == s->eof) RET(EOI);
		s->tok = s->pos = cursor; s->line++;
		goto std;
		}
#line 1061 "scanner.c"
}
#line 128 "scanner.re"


comment:

#line 1065 "scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy202;
yy203:	++YYCURSOR;
yy202:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych == '\n')	goto yy206;
	if(yych != '*')	goto yy208;
	goto yy204;
yy204:	++YYCURSOR;
	if((yych = *YYCURSOR) == '/')	goto yy209;
	goto yy205;
yy205:
#line 139 "scanner.re"
{ goto comment; }
#line 1083 "scanner.c"
yy206:	++YYCURSOR;
	goto yy207;
yy207:
#line 134 "scanner.re"
{
		if(cursor == s->eof) RET(EOI);
		s->tok = s->pos = cursor; s->line++;
		goto comment;
		}
#line 1093 "scanner.c"
yy208:	yych = *++YYCURSOR;
	goto yy205;
yy209:	++YYCURSOR;
	goto yy210;
yy210:
#line 132 "scanner.re"
{ goto std; }
#line 1101 "scanner.c"
}
#line 140 "scanner.re"

}

int lex(Scanner *s, struct Token *tok)
{
	int tokentype = scan(s);
	char *p, *q;

	tok->val = 0;
	tok->string = NULL;

	switch (tokentype)
	{
	case NUM:
		tok->val = strtol((char *)s->tok, NULL, 0);
		break;

	case STRING:
		tok->string = (char *)malloc(s->cur - s->tok - 1);
		strncpy(tok->string, (char *)s->tok + 1, s->cur - s->tok - 2);
		tok->string[s->cur - s->tok - 2] = '\0';
		for (p = q = tok->string; *p; ++p, ++q)
		{
			if (p[0] == '\\' && p[1] == '\\')
				++p;
			*q = *p;
		}
		break;

	case SYM:
		tok->string = (char *)malloc(s->cur - s->tok + 1);
		strncpy(tok->string, (char *)s->tok, s->cur - s->tok);
		tok->string[s->cur - s->tok] = '\0';
		break;
	}
	return tokentype;
}
